### PR TITLE
Solution for MSVC

### PR DESCRIPTION
**Pull request by anlismon**
With this base it's not easy to compile the library with MSVC.
Here are some WIP modifications to create the library in windows.

### CODE REVIEW

**Comment by abedra** [comment]
Hi @anlismon, thank you for starting this work! I don't do much with Windows, but I will put together something to test with shortly. In the mean time, can you please split the PRs up into build change and feature additions? I would like to keep things as separate as possible and release them in chunks to avoid issues.

I'll run through this branch on Windows and make sure the build changes still function properly in Linux.

**Comment by abedra** [comment]
In the mean time it looks like this PR broke the build, which is an indicator that it no longer works in Linux under cmake. Can you make sure to address that as well?

**Comment by anlismon** [comment]
Hello @abedra , the linux build is fixed now :). 
And you are right, I'm going to split the PR in 2, one for MSVC and other for new features.

**Comment by anlismon** [comment]
Closed to split in 2 different PR

**Pull request closed without merging**
