### PR TITLE
Add support for setting custom CA bundle path

### PR DESCRIPTION
**Pull request by jimpark**
This addresses issue #48.

However, I'm not sure if you like the idea of using std::filesystem::path. If not, we'd have to have the user convert UTF-16LE paths to UTF-8 paths on Windows. I figure this way, we let the stdlib handle it for us.

### CODE REVIEW

**Comment by abedra** [comment]
I don't mind the update here to pull in `std::filesystem::path`. My use cases all support this. If there's push back from the community it can be sorted out. Can you please update the gcc version in travis to get the build passing?

**Comment by abedra** [comment]
Thanks for the update. I'm going to run it with all the integration tests and add a test that demonstrates things work with and without this set, just for ease of mind. Do you mind if I do that on this branch? I'm also going to hit the README and make sure it properly reflects the updated requirements.

**Comment by abedra** [comment]
Just realized that you are pulling from a fork and my last comment made no sense. All merged now and I will follow on the rest before cutting a new release. Do you have any instructions you use for building and testing on Windows? I really don't have a lot of experience in that camp and would love to be able to add it to the README.

**Comment by jimpark** [comment]
It’s quite difficult because you need to actually build cURL for Windows. And that’s not an easy task either. I actually built the full chain of everything cURL needs. I still had to modify the CMakeLists.txt so that it knew where to get all libs in the dependency chain. For example, I think you need to at least build openssl with cURL to get TLS / SSL support.

Here’s someone who has documented the steps. https://albertino80.github.io/building.html

**Pull request merged**
